### ISSUE TITLE
3d viewer for schematic, litematic and mcstructure files

### ISSUE THREAD

**Issue by Max-RM** [misode/vscode-nbt#13] opened 2021-07-30 10:37 UTC
schematic files can be opened, but they are not displayed in the 3d view

**Comment by TomLewis** [comment] 2022-04-21 14:57
Bump, I came here to suggest this too!

**Comment by Lukebb04** [comment] 2022-07-14 10:56
also can you add support for construction files from Amulet [this](https://github.com/Amulet-Team/construction-specification/blob/master/specifications/README.md) might help

**Comment by magicus** [comment] 2023-11-15 12:27
Yeah, that'd like super useful!

I don't think it would be too hard. All the pieces needed to make this work is already present.

The litematica files I looked at has a  `Regions` key, containing a map from region-name to an object with `Size` (x,y,z), `BlockStatePalette` (an array of block states, like in a region file) and finally a `BlockStates` array, just like the `data` field in a region file. That is all you need to create a `Structure` object to send for rendering.

I'm guessing the one big hurdle is figuring out how to map the sequence of block states onto the 3d coordinate system as given by the size, but that's a simple trial-and-error process.

I might give it a shot, if I manage to find some spare time...

**Comment by misode** [comment] 2023-11-15 23:25
I'm interested in starting to implement this. If anyone has some litematic/schematic files from various versions that I could use to test, that would be very handy!

**Comment by magicus** [comment] 2023-11-16 09:41
And here is the oldest one I could find, from 1.15. From a quick glance, there seem to be no (relevant) difference in format.

[super_simple_tree_farm_ilmango.litematic.zip](https://github.com/misode/vscode-nbt/files/13375861/super_simple_tree_farm_ilmango.litematic.zip)

**Comment by magicus** [comment] 2023-11-16 09:57
Looking around the code and the litematica format a bit more, it seems that the storage is almost identical to structures prior to VERSION_21w43a. I think ChunkEditor.loadStructure() can be used almost straight away, with just adaptions for the size of the region, instead of the hardcoded 16x16.

**Comment by misode** [comment] 2023-11-17 04:13
I've started work on this in #57 

### Experimental download
- Download and **extract** the [vscode-nbt-0.9.0-beta.1.zip](https://github.com/misode/vscode-nbt/files/13387105/vscode-nbt-0.9.0-beta.1.zip)
- Run the `Install from VSIX` command in vscode
- If a structure does not load or shows incorrectly, please attach it here so I can take a look!

**Known problems:**
- `.schematic` files are not supported.
- `.schem` files with palettes larger than 128 blocks will be broken

@magicus @Lukebb04 @TomLewis @Max-RM

**Comment by magicus** [comment] 2023-11-17 11:35
It's looking very good! It has handled most of the files I've thrown at it, including some age-old `.schematic`. I found just two files which has problems. Funnily enough, both these were files I posted above. I must have a knack for finding problematic examples. ;-)

The first one is the [Chromoss](https://github.com/misode/vscode-nbt/files/13375656/Chromoss_2x3x2.litematic.zip) design I posted above. It loads and looks good, but when you look closely you see that there are missing blocks at the bottom; the bottom half of two "slices". (The construct is supposed to be fully symmetric; I double checked that the schematic itself is not broken by loading the schematic into a Minecraft world with Litematica.) Very odd. I'm guessing some kind of bug related to mapping the xyz coordinates to the block data stream.

The second is the [Slime farm](https://github.com/misode/vscode-nbt/files/13375657/soil_swamp_slime_25k.litematic.zip). I would have guessed it should be problematic since it has two different regions, but I don't even get to see a 3D view, just the error message "Cannot mix BigInt and other types, use explicit conversions" which more sounds like a type issue.

**Comment by Max-RM** [comment] 2023-11-18 10:32
> I've started work on this in #57
> 
> ### Experimental download
> * Download and **extract** the [vscode-nbt-0.9.0-beta.1.zip](https://github.com/misode/vscode-nbt/files/13387105/vscode-nbt-0.9.0-beta.1.zip)
> * Run the `Install from VSIX` command in vscode
> * If a structure does not load or shows incorrectly, please attach it here so I can take a look!
> 
> **Known problems:**
> 
> * Some `.schematic` files are not supported.
> * `.schem` files with palettes larger than 128 blocks will be broken
> 
> @magicus @Lukebb04 @TomLewis @Max-RM

ok will try it now

**Comment by Max-RM** [comment] 2023-11-18 10:45
@misode I tried to open several of my schematic files, but they all opened incorrectly, none of them was displayed in 3d mode and there was just an empty window. here archive: 
[schematic.zip](https://github.com/misode/vscode-nbt/files/13400044/schematic.zip)
+ this file aslo doesnt show in 3d mode https://github.com/Max-RM/-MR1331-Command_block_machine/releases/tag/0.0.1

**Comment by TomLewis** [comment] 2023-11-18 12:06
Just some feedback I'm super excited for previewing schematics in 3D, I'm on my phone so can't do any testing or upload and schematics yet, but I have an archive of schematics going back years, my Minecraft server is 11 years old! So hit me up for testing them when the time is ready!

**Comment by Max-RM** [comment] 2023-11-18 16:26
> Just some feedback I'm super excited for previewing schematics in 3D, I'm on my phone so can't do any testing or upload any schematics yet, but I have an archive of schematics going back years, my Minecraft server is 11 years old! So hit me up for testing them when the time is ready!

You're wrong. You can install Linux in proot/chroot on your phone, then install Vs code then install this NBT viewer and it will work.

https://user-images.githubusercontent.com/81485476/213984092-dd5b16ea-4a1d-4e3a-8016-a0e4267a2e7d.jpg
https://youtu.be/zKLESxTTuHE?si=9wCbG11oP3ZIvK6o

**Comment by magicus** [comment] 2023-11-19 10:58
@Max-RM Your MR1331 file looks odd. How did you create it? Just to check: it says `Materials: "Pocket"`, is this created on Bedrock Edition?

**Comment by Max-RM** [comment] 2023-11-19 11:22
> Your MR1331 file looks odd. How did you create it? Just to check: it says , is this created on Bedrock Edition?`Materials: "Pocket"`

yea this machine was exported from MCBE world using Amulet Map Editor.

**Comment by magicus** [comment] 2023-11-19 14:04
That's a whole different way to represent the world. Can you look at chunk/region data from bedrock in 3d?

**Comment by Max-RM** [comment] 2023-11-19 14:18
> That's a whole different way to represent the world. Can you look at chunk/region data from bedrock in 3d?

Yea i can via Amulet.

**Comment by magicus** [comment] 2023-11-19 21:42
I meant via the vscode-nbt editor. :-) If that is not possible, then what you are requesting is substantially different from the code in #57. That is just about reading the metadata correctly so the existing code can understand the structure that is present in litematica files.

To support bedrock files, a basic handling of the way block data is stored in bedrock is needed. I had a quick look at one of your files, and it looked substantially different. 

I see now that you opened the original bug report on schematic files, and that it was later merged with #32, support for litematica files, under the assumption (I'm guessing) that they were fairly similar in format. So in a way maybe this bug was kind of hijacked from you; I'm sorry if I was part in unwittingly doing that.

I'm guessing there actually exists two different NBT `.schematic` formats -- one used by the old Schematica Java mod, which has been superseded by Litematica. Iirc these files had a format very similar to the Litematica format.

Your `.schematic` files on the other hand are Bedrock data, and comes from Amulet. They seem to have a completely different format.

**Comment by misode** [comment] 2023-11-19 23:12
@magicus No worries, supporting the different schematic formats can be tricky, but I still want to cover all of them. The extension should be able to figure out which format it is.

However support for bedrock structures is a bit more difficult since the block IDs need to be translated. That will happen another time.

There is a new version to test: [vscode-nbt-0.9.0-beta.2.zip](https://github.com/misode/vscode-nbt/files/13404878/vscode-nbt-0.9.0-beta.2.zip)
* Fixed the issue that was causing problems with the slime farm litematic
* Added support for `.schematic`
* Block entity NBT now also shows

FYI the problem with the Chromoss litematic is likely a rendering bug, to do with a buffer being too large due to complex geometry. Feel free to open a new issue for that.

If there are still schematics not rendering correctly with this version let me know! Thanks for testing!

**Comment by Max-RM** [comment] 2023-11-20 14:48
> @magicus No worries, supporting the different schematic formats can be tricky, but definitely doable and I still want to cover all of them. The extension should be able to figure out which format it is.
> 
> However support for bedrock structures is a bit more difficult since the block IDs need to be translated. That will happen another time.
> 
> There is a new version to test: [vscode-nbt-0.9.0-beta.2.zip](https://github.com/misode/vscode-nbt/files/13404878/vscode-nbt-0.9.0-beta.2.zip)
> 
> * Fixed the issue that was causing problems with the slime farm litematic
> * Added support for `.schematic`
> * Block entity NBT now also shows
> 
> FYI the problem with the Chromoss litematic is likely a rendering bug, to do with a buffer being too large due to complex geometry. Feel free to open a new issue for that.
> 
> If there are still schematics not rendering correctly with this version let me know! Thanks for testing!

Thx. Now it can read MCBE schematics
![Снимок экрана 2023-11-20 193635](https://github.com/misode/vscode-nbt/assets/81485476/2cb72397-3f9c-42c2-a54c-712154795736)
![Снимок экрана 2023-11-20 193743](https://github.com/misode/vscode-nbt/assets/81485476/27ccac2f-5273-46d3-9c62-8ec7a4aa1eab)
![Снимок экрана 2023-11-20 193954](https://github.com/misode/vscode-nbt/assets/81485476/70a3c22b-2446-4489-a6c9-b15a09606c35)
but with some problems. In MR1331 it for some reason show blue terraccota in some places althought there is no such blocks:
![Снимок экрана 2023-11-20 194406](https://github.com/misode/vscode-nbt/assets/81485476/2eb94383-cd8d-405d-bc14-50987507a012)
True variant: 
![Снимок экрана 2023-11-20 194318](https://github.com/misode/vscode-nbt/assets/81485476/0d628aaf-701e-46eb-99e1-249b65ba4bad)
Didnt show endgateway blocks (and I think nethercore and several other exclusive MCBE blocks will be invisible): 
![Снимок экрана 2023-11-20 194556](https://github.com/misode/vscode-nbt/assets/81485476/d4e828e6-5e8f-493e-bcdc-ddd3286b12cc)
Some problems with glass althouht I dont think this will be easy to fix: 
![Снимок экрана 2023-11-20 194711](https://github.com/misode/vscode-nbt/assets/81485476/b960999a-6d92-4ac3-93e1-a723ecfba14a)

**Comment by Max-RM** [comment] 2023-11-20 14:48
Oh wait. Why honey block also invisible?

**Comment by JR1811** [comment] 2023-11-20 14:58
Seems like there are still some issues with WorldEdit `.schem` files?

- using `vscode-nbt-0.9.0-beta.2.zip`
- [WorldEdit 7.2.10 for Fabric 1.18.2](https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3697298)

---
### Files

I used [this](https://github.com/misode/vscode-nbt/files/13416219/test_schem.zip) schematic.

![schem_compare_WE](https://github.com/misode/vscode-nbt/assets/36027822/d7066b15-66e6-41ab-be21-aea4ebcb576b)

**Comment by misode** [comment] 2023-11-20 15:08
@Max-RM Bedrock `.schematic` files are only slightly working because it wrongly uses the Java numeric ID -> block state. Don't expect this to be fixed soon. Bedrock is not officially supported.

@JR1811 Thanks for your test file, I fixed that issue.

**Comment by Max-RM** [comment] 2023-11-20 15:10
What about support mcstructure files?)

**Comment by misode** [comment] 2023-11-20 15:11
> What about support mcstructure files?

@Max-RM That should be a separate issue, I don't plan to support that in this release.

**Comment by magicus** [comment] 2023-11-20 15:21
@misode I can confirm that beta 2 can show the slime farm litematica. However, it takes like forever to load; I'm guessing it needs to create a very large volume and fill it with air to transform the two regions inside a single bounding box. An alternative would be for multi-region litematicas to have a widget where you select which region you want to view, kind of like how you select chunks when looking at .mca files. What do you think about that?

**Comment by misode** [comment] 2023-11-20 15:23
@magicus Yes I had the same experience. I still need to profile why it's taking so long. Even though it is a large volume the total amount of blocks is not too crazy, so I feel like it should be a lot faster.

**Comment by magicus** [comment] 2023-11-20 15:24
Actually, I was wrong. It seems that one of the regions is indeed 136 blocks tall, so the massive amount of empty space is coming from one of the regions itself, not the combination of the two. 

Nevertheless, I think it would be beneficial to be able to study the regions separately.

**Comment by misode** [comment] 2023-11-20 23:49
I've got a new test build: [vscode-nbt-0.9.0-beta.3.zip](https://github.com/misode/vscode-nbt/files/13420317/vscode-nbt-0.9.0-beta.3.zip)

* Fixes @JR1811's issue with `.schem` files
* There should be a massive performance increase for large structures, especially ones that had lots of air (The slime farm example now loads in 5 seconds for me) @TomLewis @magicus 

Details of the performance gain: for structures with a volume larger than 48^3, computing the invisible blocks is skipped. This means that the toggle invisible blocks no longer works, but that was useless for schematics anyways, since those don't have structure voids.

**Comment by misode** [comment] 2023-11-20 23:54
> I for one would LOVE a Gallery view with a thumbnail cache.
>
> So then we can make it scan a folder in its own time, generate a cache for thumbnails for speed of use.

@TomLewis How would this work in practice? Where in vscode would the thumbnails be shown? Would there be a new window panel that shows this?

**Comment by JR1811** [comment] 2023-11-21 02:38
The example earlier works with the new version!

Other schematics are still problematic, tho.
Here are some examples:

### [bridge_test.zip](https://github.com/misode/vscode-nbt/files/13421132/bridge_test.zip)

small bridge segment made out of vanilla cobblestone material

![grafik](https://github.com/misode/vscode-nbt/assets/36027822/c6d76136-e2da-4b13-9a3e-b04fe46f050d)


### [ship.captains_quarters.schem.zip](https://github.com/misode/vscode-nbt/files/13421165/ship.captains_quarters.schem.zip)

*rooms containing mod blocks*

![bridge_test](https://github.com/misode/vscode-nbt/assets/36027822/6a4ea8e0-63df-4243-968e-292ac239facf)

**Comment by magicus** [comment] 2023-11-21 07:39
Nice! This feels much more snappy! From my point of view, this feature is close to finished.

Some UI considerations (maybe you've already thought of this):

* Is the cutoff for showing "Trying to render a very large structure" the same as for disabling invisible blocks? Maybe this fact could be shown before continuing then?

* If invisible blocks are not available, the "Show Invisible Blocks" toggle should be greyed out or removed in the GUI

* The Size display has increase/decrease arrows, but clicking any of these results in "Failed to apply edit: Invalid path size". I assume this widget should really only be read-only, to display the structure size?

**Comment by TomLewis** [comment] 2023-11-21 12:55
> > I for one would LOVE a Gallery view with a thumbnail cache.
> >
> > So then we can make it scan a folder in its own time, generate a cache for thumbnails for speed of use.
> 
> @TomLewis How would this work in practice? Where in vscode would the thumbnails be shown? Would there be a new window panel that shows this?

Good question! Lots of options!

- right click a folder creates an option "view schematics as gallery" or when you highlight multiple schematic files then the option is available?
- when already previewing a . schematic, the normal window we see now, have a button that says "see folder as gallery" with the other buttons, because most schematics are all inside the same folder already! 

Those two should cover a lot of cases then. 
The only way I've opened this window so far is by just clicking on schematic files through the browser panel on the left in vscode. I'm not aware of any other way to open it otherwise!

**Comment by misode** [comment] 2023-11-21 13:47
New build: [vscode-nbt-0.9.0-beta.5.zip](https://github.com/misode/vscode-nbt/files/13426945/vscode-nbt-0.9.0-beta.5.zip)

* Inplements @magicus' suggestions
* Fixes two issues with `.schem` files reported by @JR1811

**Comment by misode** [comment] 2023-11-21 13:48
@TomLewis Could you make a separate issue for the gallery suggestion?

**Comment by magicus** [comment] 2023-11-21 15:09
The latest test version looks ready to release, from my PoV at least. Thank you for your effort in making this possible! (Along with the rest of this plugin/deepslate, of course!)

**Closed** 2023-11-22 00:14 UTC
Labels: feature

**Comment by misode** [comment] 2023-11-22 01:14
Version `0.9.0` was just released on the VSCode Marketplace 🚀

**Comment by magicus** [comment] 2023-11-22 09:00
You might want to edit the blurb at the Marketplace to mention that it can now view schematics as well.
