### ISSUE TITLE
Blocks with missing properties don't render

### ISSUE THREAD

**Issue by Arcensoth** [misode/vscode-nbt#9] opened 2021-05-18 20:56 UTC
The block `minecraft:grass_block` does not render in the NBT structure preview.

I double-checked the NBT file (see [overgrown.zip](https://github.com/misode/vscode-nbt/files/6498947/overgrown.zip)) to confirm that the grass block does exist in the palette. I also loaded the structure in-game to verify the blocks exist and are correctly placed.

Something to do with biome tinting maybe?

![image](https://user-images.githubusercontent.com/1885643/118603914-87fbf500-b782-11eb-9e30-9c49898cb923.png)

![image](https://user-images.githubusercontent.com/1885643/118722229-eadca300-b7f9-11eb-8294-f674a30c4462.png)

**Comment by misode** [comment] 2021-05-18 23:04
The issue is that the grass block doesn't have the `snowy: false` property. Does this structure load fine in-game with the default properties?

**Comment by misode** [comment] 2021-05-20 12:43
This is fixed in d3f3a8c217a1e83d30b3dc939787ef1b66032a3c and published in version `0.5.2`.

**Closed by misode** 2021-05-20 12:43 UTC
Labels: bug
